version: "3"
services:
  mqtt-door:
    container_name: mqtt-door
    image: docker.pkg.github.com/shmick/mqtt-door/mqtt-door:latest
    restart: unless-stopped
    privileged: true
    environment:
      MQTT_USER: username
      MQTT_PASSWD: password
      MQTT_HOST: hostname